// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class updateddatabasenameaddedplanetsdbset : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateddatabasenameaddedplanetsdbset));
        
        string IMigrationMetadata.Id
        {
            get { return "202005042300057_updated database name - added planets db set"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
