// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Planetdatalayer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Planetdatalayer));
        
        string IMigrationMetadata.Id
        {
            get { return "202005042253303_Planet data layer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
